{
 "title": "Tor bridge stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tor_instance",
    "query": {
     "query": "label_values(tor_bridge_stats_countries, tor_instance)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(tor_bridge_stats_countries, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Users by country",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (country) (tor_bridge_stats_countries{tor_instance=~\"$tor_instance\", instance=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users by IP version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (ip_version) (tor_bridge_stats_ip_version{tor_instance=~\"$tor_instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users by transport",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (transport) (tor_bridge_stats_transports{tor_instance=~\"$tor_instance\", instance=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}